### ISSUE TITLE
DiamondSquare warning?

### ISSUE THREAD

**Issue by rafaqz** [EcoJulia/NeutralLandscapes.jl#39]
This warning for DiamondSquare is a bit odd:

```
Warning: DiamondSquare(0.5) cannot be run on the input dimensions (50 x 200),
│                 and will instead run on the next smallest valid size (257 x 257).
│                 This can slow performance as it involves additional memory allocation.
└ @ NeutralLandscapes ~/julia/NeutralLandscapes/src/algorithms/diamondsquare.jl:75
```

The same size problem exists in other rules, at least `PerlinNoise` - which is essentially based around making larger grids than the output grid - and we should be consistent.

I think it would make more sense to have a warning once allocations are larger than a certain size, or not have one at all and warn in the docs. Because warning for small arrays like the above isn't necessary, and once you get the warning, you're already allocating the memory.

**Comment by tpoisot** [comment]
Yeah that makes sense since there's literally nothing the user can do about it either. The grid size is the grid size is the grid size. The only issue that can arise is if the object to allocate is _really_ big, to the point where this is an `OutOfMemory` error - in this case, there is also no need for a warning since it's going to crash anyways.

100% in favor of removing this and documenting the behavior instead.

**Comment by mkborregaard** [comment]
yup!
